# Generated by Django 3.2 on 2022-09-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('cweight', models.FloatField()),
                ('tweight', models.FloatField()),
                ('activity', models.CharField(max_length=40)),
                ('goalpace', models.FloatField()),
                ('medical', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('customdt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
