# Generated by Django 3.2 on 2022-09-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0004_custommodel_primarygoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommodel',
            old_name='currentweight',
            new_name='current_weight',
        ),
        migrations.RenameField(
            model_name='custommodel',
            old_name='dailyactivity',
            new_name='daily_activity',
        ),
        migrations.RenameField(
            model_name='custommodel',
            old_name='goalpace',
            new_name='goal_pace',
        ),
        migrations.RenameField(
            model_name='custommodel',
            old_name='primarygoal',
            new_name='primary_goal',
        ),
        migrations.RenameField(
            model_name='custommodel',
            old_name='targetweight',
            new_name='target_weight',
        ),
    ]
