# Generated by Django 3.2 on 2022-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0005_auto_20220917_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewplanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('carbs', models.CharField(max_length=40)),
                ('protein', models.CharField(max_length=40)),
            ],
        ),
    ]
