# Generated by Django 3.2 on 2022-09-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0006_viewplanmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewplanmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.custommodel'),
        ),
    ]
