# Generated by Django 3.2 on 2022-09-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0007_alter_viewplanmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewplanmodel',
            name='name',
        ),
    ]
