# Generated by Django 3.2 on 2022-09-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0008_remove_viewplanmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewplanmodel',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccapp.custommodel'),
            preserve_default=False,
        ),
    ]
