# Generated by Django 3.2 on 2022-09-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0011_custommodel_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommodel',
            name='name',
        ),
    ]
