# Generated by Django 3.2 on 2022-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0018_rename_medicalconditions_custommodel_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewplanmodel',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='viewplanmodel',
            name='protein',
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='avoid_such_foods',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='bmi',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='breakfast_options',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='dinner_options',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='food_intake',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='lunch_options',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='mid_snck_options',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='tips',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='total_carbs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='total_fats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewplanmodel',
            name='total_protein',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
