# Generated by Django 3.2 on 2022-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0019_auto_20220921_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewplanmodel',
            name='total_carbs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viewplanmodel',
            name='total_fats',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viewplanmodel',
            name='total_protein',
            field=models.CharField(max_length=20),
        ),
    ]
