# Generated by Django 3.2 on 2022-09-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0021_auto_20220921_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('calories', models.FloatField()),
                ('viewdetails', models.TextField(max_length=40)),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
