# Generated by Django 3.2 on 2022-09-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0022_foodlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlistmodel',
            name='viewdetails',
        ),
    ]
