# Generated by Django 3.2 on 2022-09-28 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccapp', '0024_foodlogmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodlogModel',
            new_name='Foodlog',
        ),
        migrations.RenameField(
            model_name='foodlistmodel',
            old_name='name',
            new_name='food_name',
        ),
    ]
